#include "nav.h"
#include <ctype.h>
#include "nav_terminal.h"
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

enum { NAV_CLR_NORMAL=1,NAV_CLR_MENU,NAV_CLR_ACTIVE,NAV_CLR_SELECT,NAV_CLR_DIALOG };
static void init_colors(void){start_color();use_default_colors();init_pair(NAV_CLR_NORMAL,COLOR_WHITE,COLOR_BLUE);init_pair(NAV_CLR_MENU,COLOR_YELLOW,COLOR_BLUE);init_pair(NAV_CLR_ACTIVE,COLOR_CYAN,COLOR_BLACK);init_pair(NAV_CLR_SELECT,COLOR_BLACK,COLOR_CYAN);init_pair(NAV_CLR_DIALOG,COLOR_YELLOW,COLOR_BLUE);}
static void line(int y,int x,int width,const char*s,int pair){attrset(COLOR_PAIR(pair));mvhline(y,x,' ',width);mvaddnstr(y,x,s,width);}
static void draw_pane(const NavPane*p,int x,int y,int w,int h,bool active){char title[NAV_PATH_MAX+8],entry[512];int visible=0,row=0;snprintf(title,sizeof title," %s ",p->path);attrset(COLOR_PAIR(active?NAV_CLR_ACTIVE:NAV_CLR_NORMAL));mvaddch(y,x,ACS_ULCORNER);mvhline(y,x+1,ACS_HLINE,w-2);mvaddch(y,x+w-1,ACS_URCORNER);mvaddnstr(y,x+2,title,w-4);for(int i=1;i<h-1;i++){mvaddch(y+i,x,ACS_VLINE);mvaddch(y+i,x+w-1,ACS_VLINE);}mvaddch(y+h-1,x,ACS_LLCORNER);mvhline(y+h-1,x+1,ACS_HLINE,w-2);mvaddch(y+h-1,x+w-1,ACS_LRCORNER);
 for(size_t i=0;i<p->listing.count;i++){const NavEntry*e=&p->listing.items[i];if(p->filter[0]&&!strstr(e->name,p->filter))continue;if(visible++<p->offset)continue;if(row>=h-2)break;snprintf(entry,sizeof entry,"%-*.*s",w-2,w-2,e->name);line(y+1+row,x+1,w-2,(visible-1==p->selected)?entry:entry,(active&&visible-1==p->selected)?NAV_CLR_SELECT:NAV_CLR_NORMAL);row++;} }
static void draw(NavApp*a){int rows,cols,ph;getmaxyx(stdscr,rows,cols);erase();line(0,0,cols," File   View   Search   Transfer   Repo   Vault   Options   Help",NAV_CLR_MENU);ph=rows-4;draw_pane(&a->panes[0],0,1,cols/2,ph,a->active==0);draw_pane(&a->panes[1],cols/2,1,cols-cols/2,ph,a->active==1);if(a->panes[a->active].filter[0]){char f[300];snprintf(f,sizeof f," Filter: %s",a->panes[a->active].filter);line(rows-3,0,cols,f,NAV_CLR_DIALOG);}else line(rows-3,0,cols,a->status,NAV_CLR_NORMAL);line(rows-2,0,cols," F1 Help  F3 View  F4 Edit  F5 Copy  F6 Move  F7 MkDir  F8 Delete",NAV_CLR_MENU);line(rows-1,0,cols," F9 Menu  F10 Quit     Tab Switch     / Filter     Alt-Left/Right History",NAV_CLR_MENU);refresh();}
static int prompt(const char*label,char*out,size_t n){int rows,cols,c;size_t len=0;getmaxyx(stdscr,rows,cols);memset(out,0,n);for(;;){char b[512];snprintf(b,sizeof b," %s%s",label,out);line(rows/2,cols/4,cols/2,b,NAV_CLR_DIALOG);move(rows/2,cols/4+(int)strlen(label)+1+(int)len);c=getch();if(c==27)return -1;if(c=='\n'||c==KEY_ENTER)return 0;if((c==KEY_BACKSPACE||c==127)&&len){out[--len]=0;}else if(isprint(c)&&len+1<n){out[len++]=(char)c;out[len]=0;}}}
static void message(NavApp*a,const char*s){size_t n=strnlen(s,sizeof a->status-2);a->status[0]=' ';memcpy(a->status+1,s,n);a->status[n+1]=0;}
static void viewer(const NavEntry*e){FILE*f=fopen(e->path,"rb");char **lines=NULL,*buf=NULL;size_t cap=0,count=0;int ch,top=0,rows,cols;if(!f)return;for(;;){char temp[2048];if(!fgets(temp,sizeof temp,f))break;if(memchr(temp,0,strlen(temp))){fclose(f);endwin();printf("%s is binary\n",e->path);return;}if(count==cap){cap=cap?cap*2:128;lines=realloc(lines,cap*sizeof *lines);}lines[count++]=strdup(temp);}fclose(f);(void)buf;for(;;){getmaxyx(stdscr,rows,cols);erase();line(0,0,cols,e->path,NAV_CLR_MENU);for(int i=0;i<rows-2&&top+i<(int)count;i++){char n[16];snprintf(n,sizeof n,"%6d ",top+i+1);line(i+1,0,cols,n,NAV_CLR_MENU);mvaddnstr(i+1,7,lines[top+i],cols-8);}line(rows-1,0,cols," Esc Back   / Find   Up/Down Scroll",NAV_CLR_MENU);refresh();ch=getch();if(ch==27)break;if(ch==KEY_DOWN&&top+1<(int)count)top++;if(ch==KEY_UP&&top)top--;if(ch=='/'){char q[128];if(!prompt("Find: ",q,sizeof q))for(size_t i=(size_t)top+1;i<count;i++)if(strstr(lines[i],q)){top=(int)i;break;}}}for(size_t i=0;i<count;i++)free(lines[i]);free(lines);}
static void operate(NavApp*a,int key){NavPane*p=&a->panes[a->active],*other=&a->panes[!a->active];const NavEntry*e=nav_pane_selected(p);char input[NAV_PATH_MAX],dest[NAV_PATH_MAX],err[256];if(!e){return;}if(key==KEY_F(3)){if(e->flags&NAV_ENTRY_DIR)message(a,"Cannot view a directory");else viewer(e);return;}if(key==KEY_F(4)){endwin();char cmd[NAV_PATH_MAX+16];snprintf(cmd,sizeof cmd,"tdx '%s'",e->path);system(cmd);refresh();return;}if(key==KEY_F(5)){snprintf(input,sizeof input,"Copy to [%s]: ",other->path);if(!prompt(input,dest,sizeof dest)&&nav_path_join(other->path,dest[0]?dest:nav_path_basename(e->path),input,sizeof input)==0){if(p->provider->copy(p->provider,e->path,input,err,sizeof err))message(a,err);else{message(a,"Copy complete");nav_pane_load(other,other->path,a->show_hidden,false,err,sizeof err);}}return;}if(key==KEY_F(6)){if(!prompt("Rename to: ",dest,sizeof dest)&&dest[0]&&!nav_path_join(p->path,dest,input,sizeof input)){if(p->provider->rename_path(p->provider,e->path,input,err,sizeof err))message(a,err);else nav_pane_load(p,p->path,a->show_hidden,false,err,sizeof err);}return;}if(key==KEY_F(7)){if(!prompt("Directory name: ",dest,sizeof dest)&&dest[0]&&!nav_path_join(p->path,dest,input,sizeof input)){if(p->provider->mkdir(p->provider,input,err,sizeof err))message(a,err);else nav_pane_load(p,p->path,a->show_hidden,false,err,sizeof err);}return;}if(key==KEY_F(8)){if(!prompt("Delete? Type yes: ",dest,sizeof dest)&&!strcmp(dest,"yes")){if(p->provider->remove(p->provider,e->path,err,sizeof err))message(a,err);else nav_pane_load(p,p->path,a->show_hidden,false,err,sizeof err);}return;}}
int nav_ui_run(NavApp*a){int key;initscr();cbreak();noecho();keypad(stdscr,TRUE);init_colors();curs_set(0);message(a,"Ready");while(a->running){NavPane*p=&a->panes[a->active];draw(a);key=getch();if(key==KEY_F(10)){a->running=false;continue;}if(key=='\t'){a->active=!a->active;continue;}if(key==KEY_ALT_LEFT||key==KEY_ALT_RIGHT||key==KEY_ALT_UP){const char *target=key==KEY_ALT_LEFT?nav_history_back(&p->history):key==KEY_ALT_RIGHT?nav_history_forward(&p->history):NULL;char parent[NAV_PATH_MAX],er[256];if(key==KEY_ALT_UP){nav_path_parent(p->path,parent,sizeof parent);target=parent;}if(target&&nav_pane_load(p,target,a->show_hidden,false,er,sizeof er))message(a,er);continue;}if(key==KEY_F(9)){message(a,"File View Search Transfer Repo Vault Options Help (menu placeholders)");continue;}if(key=='/'){char f[NAV_NAME_MAX];if(!prompt("Filter: ",f,sizeof f))snprintf(p->filter,sizeof p->filter,"%s",f);continue;}if(key==27){p->filter[0]=0;continue;}if(key==KEY_UP&&p->selected)p->selected--;else if(key==KEY_DOWN&&p->selected+1<nav_pane_visible_count(p))p->selected++;else if(key==KEY_HOME)p->selected=0;else if(key==KEY_END)p->selected=nav_pane_visible_count(p)-1;else if(key==KEY_PPAGE)p->selected=p->selected>10?p->selected-10:0;else if(key==KEY_NPAGE){int n=nav_pane_visible_count(p);p->selected=p->selected+10<n?p->selected+10:n-1;}else if(key==KEY_BACKSPACE||key==127){char parent[NAV_PATH_MAX],er[256];nav_path_parent(p->path,parent,sizeof parent);if(nav_pane_load(p,parent,a->show_hidden,true,er,sizeof er))message(a,er);}else if(key=='\n'||key==KEY_ENTER){const NavEntry*e=nav_pane_selected(p);char er[256];if(e&&(e->flags&NAV_ENTRY_DIR)){char target[NAV_PATH_MAX];if(e->flags&NAV_ENTRY_PARENT)nav_path_parent(p->path,target,sizeof target);else snprintf(target,sizeof target,"%s",e->path);if(nav_pane_load(p,target,a->show_hidden,true,er,sizeof er))message(a,er);}else if(e)viewer(e);}else if(key==KEY_F(3)||key==KEY_F(4)||key==KEY_F(5)||key==KEY_F(6)||key==KEY_F(7)||key==KEY_F(8))operate(a,key);else if(key==12){char er[256];nav_pane_load(p,p->path,a->show_hidden,false,er,sizeof er);} }endwin();return 0;}
